# Week 1 : Introduction to Python

# Python Basics

## Python as a calculator
- `+`, `-`, `*`, `/`
- Exponentiation : `**`
- Modulo : `%` -> returns the remainder

In [3]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

10
0


In [2]:
# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

15
5.0
4
16


In [5]:
# How much is your $100 worth after 7 years? (10% 연이율로 7년년)
print(100 * (1.1 **7))

194.87171000000012


## Variable and Types
- Variable
    * specific, case-sensitive name
    * can call up value through variable name
    * use `=` to assign  

    
- Type : `type()`
    * `float` & `int`
    * `str` : text, use `''` or `""`
    * `bool` : True, False
- How the codes act depends on the types of variables

In [8]:
# Create a variable savings & variable growth_multiplier
savings = 100 # python = sign DOES NOT test equality - assignment operator
growth_multiplier = 1.1

In [10]:
# Calculate result and print
result = savings*growth_multiplier**7
print(result)

194.87171000000012


In [12]:
# strings and booleans
desc = "compound interest"

In [11]:
year1 = savings*growth_multiplier
print(type(year1))

<class 'float'>


In [13]:
# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc
print(doubledesc) # just pastes the strings together

compound interestcompound interest


In [14]:
# How the codes act depends on the types of variables
savings = 100
result = 100 * 1.10 ** 7

In [15]:
# + pastes the strings together
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

I started with $100 and now have $194.87171000000012. Awesome!


In [16]:
# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

# Python Lists

## Lists
- `[a, b, c]` : use square brackets to create a list
- can contain any type of variable, lists can contain lists (sublists)

In [17]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [19]:
# lists can contain various types
areas = ['hallway', hall, 'kitchen', kit, "living room", liv, 
'bedroom', bed, "bathroom", bath]
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [22]:
# list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]
print(house)
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


## Subsetting lists
- start from 0 (zero-indexing)
- `listname[index]`
- from behind - use *negative* index
- certain range - use `start : end` (list slicing), end is ***NOT*** included
- to subset lists of lists : use 2 square brackets - `var[index1][index2]`

In [23]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

In [24]:
# Print out second element from areas - zero indexing
print(areas[1])

# Print out last element from areas - negative indexing
print(areas[-1])

# Print out the area of the living room - the 6th element
print(areas[5])

11.25
9.5
20.0


In [25]:
# using indexing for calculation
eat_sleep_area = areas[3] + areas[-3]
print(eat_sleep_area)

28.75


In [26]:
# slicing
downstairs = areas[:6] # 0 ~ 6
upstairs = areas[-4:] # 뒤에서 4번쨰~마지막
print([downstairs, upstairs])

[['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0], ['bedroom', 10.75, 'bathroom', 9.5]]


In [29]:
# subsetting lists of lists
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
print(x[2][0])
print(x[2][:2])

g
['g', 'h']


## Manipulating lists
- changing lists : assign new elements by using `=`
- adding elements : `list1 + list2`
- removing elements : `del(list[index])` - be aware of changes in indices
- when copying lists, use `list(x)` or `x[:]` 

In [30]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

In [31]:
# changing values
# Correct the bathroom area
areas[-1] = 10.5
# Change "living room" to "chill zone"
areas[4] = 'chill zone'
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [32]:
# adding values
# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ['poolhouse', 24.5]
# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ['garage',15.45]
print(areas_1)
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


In [33]:
# deleting values
x = ["a", "b", "c", "d"]
del(x[1])
print(x)

['a', 'c', 'd']


In [34]:
# deleting values, with the areas ex.
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
# deleting the poolhouse
del(areas[-4:-2])
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [36]:
# inner workings of lists
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
areas_copy = areas[:]
# manipulate areas_copy
areas_copy[0] = 5.0
print(areas) # not affected
print(areas_copy) # modified

[11.25, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


# Functions and Packages

## Functions
- piece of reusable code -> call functions instead of rewriting codes
- Built-in functions examples
    * `max()`, `type()`
    * `round(number, ndigits)` : ndigits default = NONE -> optional arg
    * `help()` : documentation of functions

In [2]:
# print(), type(), str(), int(), bool(), float(), len()
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)
type(out2)

<class 'list'>
4


int

In [3]:
# help()
help(pow) # base, exp, mod args

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [4]:
# sorted()
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True) # reverse option - max to min

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


## Methods
- call functions on objects
    - all Python variables are objects
- using the **`.`** operator
    - ex) list methods: `fam.index("mom")` / `fam.count(1.73)`
    - ex) str methods: `sister.capitalize()` / `sister.replace("z", "sa")`

In [5]:
# String methods
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up : upper()
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place : count()
print(place.count('o'))

poolhouse
POOLHOUSE
3


In [6]:
# List methods 1
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0 : index()
print(areas.index(20.0))

# Print out how often 9.50 appears in areas : count()
print(areas.count(9.50))

2
1


In [8]:
# List methods 2
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size : append()
areas.append(24.5)
areas.append(15.45)
print(areas)

# Reverse the orders of the elements in areas : reverse()
areas.reverse()
print(areas)

# Removing
areas.remove(9.5)
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]
[15.45, 24.5, 10.75, 20.0, 18.0, 11.25]


## Packages
- directory of Python scripts, each script : module
- ex) NumPy, Matplotlib, scikit-learn
1. Install package
    - Terminal -> `python3 get-pip.py` / `pip3 install numpy`
2. Import package
    - `import` ex) `import numpy`
    - `import package as name` : import the package as a simpler name
    - `from package import function` : use specific parts of the package

In [10]:
# Import basic
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C (둘레)
C = 2*math.pi*r

# Calculate A (넓이)
A = math.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [11]:
# Selective import using "from ~ import ~"
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
deg = 12
dist = r*radians(deg)

# Print out dist
print(dist)

40317.10572106901


In [15]:
# from ~ import ~ as ~
from scipy.linalg import inv as my_inv
my_inv([[1,2], [3,4]]) # inverse matrix, requires sqaure matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# NumPy

## NumPy Array
- Alternative to Python List
- Calculation over entire arrays
- `import numpy as np`
- Creating an array : `np.array()`
- NumPy arrays can contain only ***one*** type
- NumPy arrays have different methods
- Subsetting
    - Can use comparisons
    - Can use these comparisons as index

In [16]:
# Create list baseball : height in centimeters
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [18]:
# Calculation using arrays
# Con
np_baseball_m = np_baseball / 100
print(np_baseball_m)

array([1.8 , 2.15, 2.1 , 2.1 , 1.88, 1.76, 2.09, 2.  ])

In [27]:
# Indexing
x = [4 , 9 , 6, 3, 1]
print(x[1])
y = np.array(x)
print(y[1])

# Works the same with Python lists
x = ["a", "b", "c"]
print(x[1])

np_x = np.array(x)
print(np_x[1])

9
9
b
b


In [24]:
# Indexing using boolean
high = y > 5
y[high]

array([9, 6])

In [25]:
# Numpy arithmetical operators work differently from Python lists
np.array([True, 1, 2]) + np.array([3, 4, False]) # True: 1, False: 0

array([4, 5, 2])

## 2D NumPy arrays
- Create from a list of lists, improved version
- `shape` : see the structure of the array
- `array[row][col]` / `array[row, col]` / use colons to slice

In [28]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [34]:
# Indexing and slicing
# Print out the 4th row of np_baseball
print(np_baseball[3,:])

# Select the entire second column of np_baseball
np_weight_lb = np_baseball[:,1]

# Print out height of 2nd player
print(np_baseball[1, 0])

[188.   75.2]
215.0


In [35]:
# 2D arithmetics : works the same
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print(np_mat + np.array([10, 10]))
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


## NumPy: Basic Statistics
- `np.mean()`
- `np.median()`
- `np.corrcoef()` : correlation
- `np.std()` : standard deviation
- `np.round(random.normal())` : was used to create data used in the exercises

In [39]:
# Mean and median
import numpy as np
x = [1, 4, 8, 10, 12]
np_x = np.array(x)
print(np.mean(np_x))
print(np.median(np_x))

7.0
8.0


In [49]:
# Standard deviation and correlation
y = [2, 6, 7, 14, 15]
np_y = np.array(y)

# Mean
avg_x = np.mean(np_x)
avg_y = np.mean(np_y)
print("Mean of %s, %s: %f, %f" %("x", "y", avg_x, avg_y))

# Median
med_x = np.median(np_x)
med_y = np.median(np_y)
print("Median of %s, %s: %f, %f" %("x", "y", med_x, med_y))

# Standard deviation
std_x = np.std(np_x)
std_y = np.std(np_y)
print("Standard deviation of %s, %s: %f, %f" %("x", "y", std_x, std_y))

# Correlation coefficient
cor = np.corrcoef(np_x, np_y)
print("Correlation of %s, %s: %s" %("x", "y", str(cor)))

Mean of x, y: 7.000000, 8.800000
Median of x, y: 8.000000, 7.000000
Standard deviation of x, y: 4.000000, 4.955805
Correlation coefficient of x, y: [[1.         0.94838282]
 [0.94838282 1.        ]]
