#1주차 과제
- 파이토치 시작하기 및 간단한 코드 빈칸 채워넣기

#파이토치 시작하기

파이토치 시작하기

In [1]:
import torch 

- tensor 개념 파악 (array of numerical values(vector, matrix..))
- 4x3 행렬 두개 만들고 행으로 병합, 열로 병합


In [78]:
X = torch.tensor([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])
Y = torch.tensor([[3,2,1],[6,5,4],[9,8,7],[12,11,10]])
# display(X,Y)
###행으로 병합 코드
print('행으로 병합 : ')
print(torch.cat((X,Y), dim = 0))
###열로 병합 코드
print('열로 병합 : ')
print(torch.cat((X,Y), dim = 1))

행으로 병합 : 
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [ 3,  2,  1],
        [ 6,  5,  4],
        [ 9,  8,  7],
        [12, 11, 10]])
열로 병합 : 
tensor([[ 1,  2,  3,  3,  2,  1],
        [ 4,  5,  6,  6,  5,  4],
        [ 7,  8,  9,  9,  8,  7],
        [10, 11, 12, 12, 11, 10]])


linear regression implementation from scratch
- 머신러닝 기초와 비슷한 내용이지만 파이토치로 실행해보며 익숙해지는것이 목표


In [12]:
!pip install --upgrade pip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 37.3 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4


In [17]:
# !pip install d2l

In [16]:
!pip install --upgrade d2l

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [22]:
!pip install matplotlib_inline

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [23]:
%matplotlib inline
import random
import torch
from d2l import torch as d2l

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [79]:
def synthetic_data(w, b, num_examples):
    """Generate y = Xw + b + noise."""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

true_w = torch.tensor([3, -1.5])
true_b = 5.5
features, labels = synthetic_data(true_w, true_b, 2000)

In [80]:
print('features:', features[0],'\nlabel:', labels[0])

features: tensor([ 1.0437, -1.7843]) 
label: tensor([11.3150])


In [81]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # The examples are read at random, in no particular order
    random.shuffle(indices)
    ###반복문으로 채워넣기:
    for i in range(0,num_examples, batch_size):
        ##이하는 반복문에 대한 조건입니다.
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [82]:
batch_size = 20

for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break

tensor([[-2.0198,  1.7625],
        [ 0.0454,  0.0034],
        [-0.4248, -0.7368],
        [ 1.6128, -1.0989],
        [ 0.4492,  1.8408],
        [-1.1165, -0.4374],
        [ 0.4616,  0.6334],
        [-0.8746, -1.4948],
        [-1.2808, -2.9983],
        [ 0.0462,  1.1396],
        [-1.5332,  1.1093],
        [-1.3689,  0.1610],
        [-2.1259, -0.4048],
        [-0.7750,  0.2192],
        [ 0.9108, -0.0970],
        [ 2.2371, -1.0408],
        [-0.8293,  0.6721],
        [-0.5975, -0.3446],
        [ 0.4453,  1.3676],
        [-0.8318, -1.7449]]) 
 tensor([[-3.2283],
        [ 5.6264],
        [ 5.3325],
        [11.9999],
        [ 4.0848],
        [ 2.8076],
        [ 5.9414],
        [ 5.1241],
        [ 6.1393],
        [ 3.9407],
        [-0.7391],
        [ 1.1431],
        [-0.2710],
        [ 2.8395],
        [ 8.3709],
        [13.7588],
        [ 2.0228],
        [ 4.2473],
        [ 4.7859],
        [ 5.6225]])


In [101]:
w = torch.normal(0, 0.01, size=(2,1), requires_grad=True)
b = torch.tensor([2.], requires_grad = True)#원하는 실수를 넣어주세요

In [84]:
def linreg(X, w, b):
    """The linear regression model."""
    return torch.matmul(X, w) + b

In [85]:
def squared_loss(y_hat, y):  
    """Squared loss."""
    return (y_hat - y.reshape(y_hat.shape)) ** 2 / 2

In [86]:
def sgd(params, lr, batch_size):
    """Minibatch stochastic gradient descent."""
    with torch.no_grad():
        for param in params:
            param -= lr * param.grad / batch_size
            param.grad.zero_()

In [102]:
lr = 0.03
num_epochs = 3
net = linreg
loss = squared_loss

for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, features, labels):
        l = loss(net(X, w, b), y) 
        # Compute gradient on `l` with respect to [`w`, `b`]
        l.sum().backward()
        sgd([w, b], lr, batch_size) 
    with torch.no_grad():
        train_l = loss(net(features, w, b), labels)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')

epoch 1, loss 0.035331
epoch 2, loss 0.000171
epoch 3, loss 0.000050


In [50]:
print(f'error in estimating w: {true_w - w.reshape(true_w.shape)}')
print(f'error in estimating b: {true_b - b}')

error in estimating w: tensor([ 2.9703, -1.4355], grad_fn=<SubBackward0>)
error in estimating b: tensor([4.5000])


+cost graph 그리기 (x축 w, y축 loss)

In [104]:
w, l

(tensor([[ 2.9992],
         [-1.4998]], requires_grad=True), tensor([[1.9111e-08],
         [1.0821e-05],
         [2.4640e-06],
         [4.9712e-05],
         [3.1491e-05],
         [8.7036e-05],
         [2.1950e-06],
         [1.5384e-05],
         [3.3127e-07],
         [1.6928e-05],
         [1.7368e-05],
         [2.0065e-05],
         [3.5992e-05],
         [1.1618e-05],
         [7.7829e-06],
         [3.5786e-06],
         [5.3236e-06],
         [5.7176e-05],
         [1.5403e-07],
         [4.1203e-05]], grad_fn=<DivBackward0>))

concise implementation of linear regression 
- api 사용해보기

In [60]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l


true_w = torch.tensor([3, -1.5])
true_b = 5.5
features, labels = d2l.synthetic_data(true_w, true_b, 2000)

In [61]:
def load_array(data_arrays, batch_size, is_train=True): 
    """Construct a PyTorch data iterator."""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 20
data_iter = load_array((features, labels), batch_size)

In [62]:
next(iter(data_iter))

[tensor([[-0.1907,  1.1079],
         [-0.2745, -0.5122],
         [-0.8318,  0.4420],
         [-2.2728, -0.5102],
         [ 0.3089, -3.1004],
         [-0.1305,  0.4615],
         [-0.8309, -1.0508],
         [-1.0785, -0.8291],
         [-0.9284, -0.2439],
         [ 1.3080,  0.4111],
         [-0.2599,  1.4381],
         [ 0.0552,  0.8836],
         [ 1.0281,  1.0051],
         [ 0.5990, -0.5328],
         [ 1.5848,  1.0470],
         [-1.7469, -0.3409],
         [-1.7504,  0.9285],
         [-1.1819,  0.7824],
         [-0.1747, -0.6811],
         [-1.1223,  0.1494]]), tensor([[ 3.2733],
         [ 5.4313],
         [ 2.3593],
         [-0.5719],
         [11.0873],
         [ 4.4184],
         [ 4.5834],
         [ 3.5112],
         [ 3.0807],
         [ 8.8058],
         [ 2.5649],
         [ 4.3227],
         [ 7.0823],
         [ 8.0805],
         [ 8.6972],
         [ 0.7756],
         [-1.1552],
         [ 0.7864],
         [ 5.9951],
         [ 1.9027]])]

In [64]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

In [65]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [66]:
loss = nn.MSELoss()

In [67]:
trainer = torch.optim.SGD(net.parameters(), lr = 0.03)

In [68]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000261
epoch 2, loss 0.000104
epoch 3, loss 0.000104


In [74]:
w = net[0].weight.data
print('error in estimating w:', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('error in estimating b:', true_b - b)

error in estimating w: tensor([-0.0006, -0.0006])
error in estimating b: tensor([1.1921e-05])
